// Generated by CoffeeScript 1.7.1
(function() {
  var Result, SetIndex;

  Result = require('../result');

  SetIndex = (function() {
    function SetIndex() {
      this._map = {};
    }

    SetIndex.prototype.add = function(id, key) {
      var keys, _i, _len;
      keys = key instanceof Array ? key : [key];
      for (_i = 0, _len = keys.length; _i < _len; _i++) {
        key = keys[_i];
        if (this._map[key] == null) {
          this._map[key] = new Result();
        }
        this._map[key].add(id);
      }
      return null;
    };

    SetIndex.prototype.search = function(keys) {
      var key, results;
      if (this._map[keys] != null) {
        return this._map[keys].clone();
      } else {
        if (!(keys instanceof Array)) {
          return new Result();
        }
      }
      results = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          if (this._map[key] != null) {
            _results.push(this._map[key]);
          }
        }
        return _results;
      }).call(this);
      return Result.union(results);
    };

    return SetIndex;

  })();

  module.exports = SetIndex;

}).call(this);
