// Generated by CoffeeScript 1.7.1
(function() {
  var Helper;

  Helper = (function() {
    function Helper() {}

    Helper.hitByRaycast = function(target, points) {
      var hit, i, j, l, pointi, pointj, x, y;
      hit = false;
      l = points.length;
      i = 0;
      j = l - 1;
      x = target[0];
      y = target[1];
      while (i < l) {
        pointi = points[i];
        pointj = points[j];
        if ((pointi[1] >= y) !== (pointj[1] >= y) && (x <= (pointj[0] - pointi[0]) * (y - pointi[1]) / (pointj[1] - pointi[1]) + pointi[0])) {
          hit = !hit;
        }
        j = i;
        i++;
      }
      return hit;
    };

    Helper.squaredDistanceBetween = function(point1, point2) {
      var x, y;
      x = point1[0] - point2[0];
      y = point1[1] - point2[1];
      return x * x + y * y;
    };

    Helper.distanceBetween = function(point1, point2) {
      return Math.sqrt(Helper.squaredDistanceBetween(point1, point2));
    };

    Helper.clone = function(old) {
      var i, n, v;
      n = (old instanceof Array ? [] : {});
      for (i in old) {
        v = old[i];
        n[i] = typeof v === "object" ? this.clone(v) : v;
      }
      return n;
    };

    return Helper;

  })();

  module.exports = Helper;

}).call(this);
